-- Disable Row Level Security (RLS) on all tables
-- This allows the service role to access all tables

ALTER TABLE IF EXISTS users DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS schools DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS subjects DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS curricular_goals DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS competencies DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS learning_outcomes DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS lo_rubric_descriptors DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS activities DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS activity_rubrics DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS chapter_terms DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS rubric_submissions DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS self_reflections DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS teacher_feedback DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS term_summaries DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS part_a_students DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS part_a4_parents DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS exam_papers DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS exam_questions DISABLE ROW LEVEL SECURITY;

-- Grant necessary permissions to service role
GRANT ALL ON ALL TABLES IN SCHEMA public TO service_role;
GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO service_role;
GRANT ALL ON ALL FUNCTIONS IN SCHEMA public TO service_role;

-- Grant usage on schema
GRANT USAGE ON SCHEMA public TO service_role;
